= Code As You Would Order A Burger
:published_at: 2013-06-09
:hp-tags: OO, Design, GOOS, Tell Don't Ask, Messaging, Functional, FP

Recently during my work, I came across some code where the paradigm **Tell Don't Ask** came into play. You sometimes see code written that's not really using OO to its full strengths and still is of a procedural stance. There's often frequent examples where an object asks other objects for data and then does something with it. This is not really OO even though you may still be using other aspects of OO such as enscapulation, inheritance or polymorphism. It's still asking for data whereas the real value-add for OO is message passing or the behaviour of the objects rather than the data they may contain. I've come to understand this implicitly via the usage of mocks during testing. The use of mocks results in code that better follows the **Tell, Don't Ask** paradigm.

One of the originators of mock objects noted that:


[quote, Tim Mickinnon, A Brief History Of Mock Objects]
____
The trigger for our original discovery of the technique was when John Nolan set the challenge of writing code without getters. Getters expose implementation, which increases coupling between objects and allows responsibilities to be left in the wrong module. Avoiding getters forces an emphasis on object behaviour, rather than state, which is one of the characteristics of Responsibility Driven Design.
____ 
 

+ 
Once I came over this mental hurdle, I found I wasn't primarily concerned with the data passed between the objects but really that the appropriate methods calls or methods (messages) between objects were observed. I used the https://code.google.com/p/mockito/[Mockito mocking library] and I find the most of my tests are interaction tests i.e. verifying that methods calls were made in the manner expected. State based testing is still important but at the right place. This got me thinking about objects in terms of http://c2.com/cgi/wiki?AlanKaysDefinitionOfObjectOriented[Alan Kay's emphasis on message passing] . The following examples illustrates why telling an object to do something rather than asking it for its data is better. 

I work a lot with enterprise integration and one of the examples that illustrates this point is message concatenation. During conversion from a 
internal message to one that that is supported by an external protocol, dependent on whether a message is concatenated or not, then the message may be decorated with extra parameters to indicate that it is a multipart message rather than a single message.

In this example the extra metadata parameters that get added are:

* The message reference for the multipart message
* The part number of the message
* Total number of parts for the message

====== Implementation Using An Ask Approach

A factory was used to create a map of parameters for message concatenation:

++++
<script src="https://gist.github.com/bigkahuna1uk/5744388.js"></script>
++++


The protocol converter that used this information was coded like this:

++++
<script src="https://gist.github.com/bigkahuna1uk/5744407.js"></script>
++++

This was bad for several reasons:

* The MultipartMessageParameterFactory returns an abstract datatype, in this case a map, so users of this class have to know what keys to pull out the data. If this approach really must be followed, a domain object to hold the multipart parameters would be better, maybe a simple POJO with accessors for the different parameters.
* The main problem with this approach is it results in http://c2.com/cgi/wiki?InappropriateIntimacy[Inappropriate Intimacy]. The user is asking for some data and then assembling that data thereafter. The lookup keys for the map are made  public presumably to mistakenly enforce DRY principles for magic strings within a unit test. 
* This class could become better by passing in the parameter factory in the constructor so it can be mocked. In this way the unit test for this class will be simpler but it's still complicated.  



====== Implementation Using A Tell Approach

The **Tell** is all about telling an object to perform some piece of work on your behalf rather than asking that object for data and then doing the work yourself. In the previous example, the protocol converter asked another object for the message concatenation info and then added those parts itself to the message. In the following example, we ask another object to do this bit of work for us. Firstly we introduce a domain object to replace the map use for the multipart parameters:

++++ 
<script src="https://gist.github.com/bigkahuna1uk/5744734.js"></script> 
++++

The factory now returns this POJO instead of the naked ADT:

++++
<script src="https://gist.github.com/bigkahuna1uk/5744751.js"></script>
++++

Now the converter asks another object, MultiPartMessageUpdater, to do the message updating:

++++
<script src="https://gist.github.com/bigkahuna1uk/5744436.js"></script>
++++

The code for updating the message is pushed into its own class. As well as enforcing the single responsibility principle, it also endorses the http://en.wikipedia.org/wiki/Command%E2%80%93query_separation[command and query separation principle] so that the retrieval of the actual parameters (query) is separated from the addition of the those parameters to the message itself (command).

++++
<script src="https://gist.github.com/bigkahuna1uk/5744526.js"></script>
++++

As a byproduct, the test for the converter becomes very simple. Beforehand we would have to test every permutation of concatenated parameters. Now because code has been pushed to their logical place the test boils down to just testing the following behaviour:

* Message should be updated if message is part of a multipart message
* Message should be untouched if message is just a single message

++++
<script src="https://gist.github.com/bigkahuna1uk/5744650.js"></script>
++++

The permutation for those 3 message parameters are pushed to where it should be namely the test for the MultipartMessageParameterFactory. Each test then tests what it should instead of testing the unit and all of its dependencies' behaviour at the same time resulting in a combinatorial explosion of test methods making the test unclear.

====== Conclusion

* We've now got a class which now asks other classes do work i.e. operation requests instead of asking for data and doing the work ourselves.
* By following this approach the http://en.wikipedia.org/wiki/Single_responsibility_principle[single responsibility principle] naturally falls out. Each class performs a single well understood operation and only that operation. This makes those classes loosely coupled and become candidates for reuse in different contexts if needed.
* Unit tests have become clearer and focused as they only testing a single object rather than a multitude. If you notice I've endeavoured to use constructor injection for any dependencies. This makes the testing of classes easier as I can mock out any external dependencies.


TIP: I remember this **Tell Don't Ask** paradigm by thinking what you would do if you ordered a burger in McDonalds. Would you ask the server for two sliced bun halves, some mayo, lettuce, a hamburger, cheese and tomato sauce or would you just ask for a Big Mac? :D
