= Immutability 
:published_at: 2016-02-28
:hp-tags: Functional Programming, Immutability, Fluent APIs, Builders, Aneamic objects, Factories, Guava, Functions


Complex anaemic object

Long constructor

Construct objects with long constructor or setters which are error prone.  How do I know object is actually fit for purpose. 


TODO: Long constructor example

TODO: Setter example

Mutable objects are inherently not thread safe


An immutabe object is one that cannot be modified after its creation. ted. 


The advantages of immutable obejects are:

* You can think of them as values. A value cannot be changed.  If a new value is required, a new object representing the new value needs to be construct


* They are inherently thread-safe. They allow safe access concurrently.
* Code based on immutable objects are easier to reason about and have a higher probability of consistent, well understood behaviour. Unexpected changes cannot occur.


TODO: Static factories alleviate issue


=== How we enforce immutability


TODO: 

* Objects with a well defined constructor
* No mutator methods on object only accessor. 


TODO: COde example








==== We have Immutable Objects But What About Collections?

Now we have a dilemma.  

You may have a collection with a list of immutable objects but the list itself may not be immutable. 


Another example is having an object with a collection. Ostensibly the object looks immutable but you can still change the contents of the list. The list itsellf is not immutable. The old way from Java 2 would be to use one of the method from Collections to create an unmodifiable list which throws a runtime exception when an attempt is made to change the list's contents




=== Immutables.io to the rescue

Fortunately there's now a library that can solve thse so







==== Guava



[source,java]
----
require 'asciidoctor'  # <1>

puts Asciidoctor.convert_file('sample.adoc', :header_footer => true)  # <2>
----
<1> Imports the library
<2> Reads, parses and renders the file

==== PCollections